sudo: requied
dist: thrusty

language: cpp

before_install:
  #- sudo apt-get -qq update
  #- sudo apt-get install -y libxml2-dev
 
install:
  # /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  # /usr/bin/clang is 3.5, lets override with modern one.
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      #- gcc-4.9
      #- g++-4.9
      - clang-3.7
      - libc++-dev 
      - libc++abi-dev

compiler:
  - clang

script:
  - mkdir build
  - cd build
  - export CXXFLAGS="-stdlib=libc++"
  - cmake .. && make -j3 VERBOSE=1
  - ./main
