sudo: requied
dist: thrusty

language: android

matrix:
  include:
    - os: linux
      compiler: "xxx-gcc"
      env: CXX="g++-5" CC="gcc-5"
    - os: linux
      compiler: "xxx-clang"
      env: CXX="clang++-3.7" CC="clang-3.7"
    - os: osx
      compiler: "xxx-clang"

before_install:
  - sudo apt-get -qq update
  #- brew install openssl
  #- sudo apt-get install -y libxml2-dev
  #

install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-5
      - g++-5
      - clang-3.7
      - libc++-dev 
      - libc++abi-dev
      - gperf
      - clang-tidy-3.8

script:
  - mkdir build
  - cd build
  #- export CXXFLAGS="-stdlib=libc++"
  - cmake ../cpp_test/ && make -j3 VERBOSE=1
  - ./main
